### ISSUE TITLE
Filament (Fuse core calculus) Tracker

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/dahlia#139]
@apurvakoti and @rachitnigam are working on a core calculus for Fuse. The calculus is implemented in Racket Redex.

### Todo
- [x] Implement simple language with stores (@apurvakoti assigned)
- [x] Add arrays to the model
- [ ] Add source level type checking rules
- [x] Implement reduction rules

**Comment by apurvakoti** [comment]
Progress can be viewed on the `filament` branch.

**Comment by rachitnigam** [comment]
Sweet!!

**Comment by apurvakoti** [comment]
Pull request link: #168
